-- This file allow to write SQL commands that will be emitted in test and dev.
-- The commands are commented as their support depends of the database
-- insert into myentity (id, field) values(1, 'field-1');
-- insert into myentity (id, field) values(2, 'field-2');
-- insert into myentity (id, field) values(3, 'field-3');
-- alter sequence myentity_seq restart with 4;

CREATE SCHEMA IF NOT EXISTS DB_FINANCAS;

CREATE SEQUENCE IF NOT EXISTS DB_FINANCAS.Seq_ID
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS DB_FINANCAS.SETOR (
    ID INT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    DESCRICAO VARCHAR(400)
);

INSERT INTO DB_FINANCAS.SETOR (ID,NOME,DESCRICAO) VALUES (1,'FINANCEIRO','BANCOS');

CREATE TABLE IF NOT EXISTS DB_FINANCAS.TIPO_ATIVO (
    ID INT PRIMARY KEY,
    NOME_TIPO_ATIVO VARCHAR(45) NOT NULL,
    DESCRICAO VARCHAR(400)
);

INSERT INTO DB_FINANCAS.TIPO_ATIVO (ID,NOME_TIPO_ATIVO, DESCRICAO) VALUES (1,'financeiro','ativo financeiro');

-- CREATE TABLE DBFINANCAS.ATIVO (
--     ID INT PRIMARY KEY,
--     NOME VARCHAR(45) NOT NULL,
--     TICKER VARCHAR(45) NOT NULL,
--     DATA_FUNDACAO DATE NOT NULL,
--     ID_SETOR INT NOT NULL,
--     ID_TIPO_ATIVO INT NOT NULL,
--     FOREIGN KEY (ID_SETOR) REFERENCES DBFINANCAS.SETOR(ID),
--     FOREIGN KEY (ID_TIPO_ATIVO) REFERENCES DBFINANCAS.TIPO_ATIVO(ID)
-- );

-- INSERT INTO DBFINANCAS.ATIVO(ID,NOME,TICKER,DATA_FUNDACAO,ID_SETOR,ID_TIPO_ATIVO) VALUES (1,'ativo 1','ticker 1','2020-01-01',1,1);

-- CREATE TABLE DBFINANCAS.COTACAO (
--     ID INT PRIMARY KEY,
--     ID_ATIVO INT NOT NULL,
--     DATA TIMESTAMP NOT NULL,
--     COTACAO FLOAT NOT NULL,
--     FOREIGN KEY (ID_ATIVO) REFERENCES DBFINANCAS.ATIVO(ID)
-- );

-- CREATE TABLE DBFINANCAS.HISTORICO_COTACAO (
--     ID INT PRIMARY KEY,
--     ID_ATIVO INT NOT NULL,
--     DATA TIMESTAMP NOT NULL,
--     COTACAO FLOAT NOT NULL
-- );


-- DROP TABLE IF EXISTS SETOR;
-- DROP TABLE IF EXISTS TIPO_ATIVO;
-- DROP TABLE IF EXISTS COTACAO;
-- DROP TABLE IF EXISTS HISTORICO_COTACAO;
-- DROP TABLE IF EXISTS ATIVO;

-- DROP SEQUENCE Seq_ID;
-- DROP DATABASE dbFinancas;
-- DROP SCHEMA dbFinancas;